import diophantine_inequalities_11d79_congruences_many_foundation_canonical_lane_mathlib.GateLemmas
import diophantine_inequalities_11d79_congruences_many_foundation_canonical_lane_mathlib.FinalTheorem
